language: node_js
node_js:
- '6'

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=develop
  - DOCKER_SRC_IMAGE=ram-frontend
  - DOCKER_REPOSITORY=wbtransport/ram-frontend
  - DOCKER_USERNAME=danielfdsilva
  # DOCKER_PASSWD
  - secure: "h75xWtn6FcviGqtw0nkL1WXl+v64xsCDI3gGIZWrDg5BO5Mg2YRUARPRsoGWFL6HcHuDNdVzG/yxacwdGaGbUlLjnmUk9g/8NMWzvY/4viFduuW/WYO3JbnVzXbHhowAoFi1JyLfo3ZKi4Ci2+kcL6HqlZNJfpkAwR0j0oxc9GMZn11Wk7JWjJoU5+eUTU0MJ6cZn+hpABzw+h9VQSevU6AgxTFYAMyfCQ83PnBjZjoovK9UU98E4L1UvISw8mGUPzYVb6I45HGrQQ5Ts7dD0/3M7eHG/Wct6Rn7Jr9bdnrTXWRbOz8v8FuzWOFn3WyH9JqRbeZzA+BoO1haBVHt6uiFrEDNEPx/YPOob14eNrUgnTZW6ywd1DSbj809hrYexClgcbIvErUV2KHectv2tFNVMBGj25SgT7DvqDbqd6SuYJnCn8hU8c8OqNaimhppYHyWnGJyAcIjnqzXWy2OGRu0G/aTVnlY7KQu4RVbLBUCSveQnNoG/OdyEyx7H50mXcUXU8686MXn4KolxTsw8PTFJ3G4DVhGzMXDpx9vxCStEYV1t2Tkfwj2mUObn/K1GxyaiUKlz7wUbrQ6eV2JN71OujpVU9RSyk6bM5wYjPitf8P6Sj+/k+5XR6arR3wGMdWgJn5p5uVSCr1U2qaaC67AqYx18jq/OGp0g1KJNmY="

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

# Skip the installation step
install: true

services:
  - docker

deploy:
- provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${STAGING_BRANCH}"
- provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
