language: node_js

node_js:
- '6'

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=develop
  - AWS_REGION=us-east-1
  - AWS_ECS_CLUSTER=ruralroads
  - DOCKER_SRC_IMAGE=rra-dashboard
  - DOCKER_REPOSITORY=wbtransport/rra-dashboard
  - secure: "qg9OaApdYO6im/5iJF0WoB/+otlrjG8uYgyOLkKyK3G5UI7WSCeDH16vvMlKHmk+HVEaC5/3IofVCHJgUpI9T7QymC2b0EcGixZ0yb50YH9KlSNUcDusZOHvSUTKHV4si7b/dNS/fQ3SOrE+YF3lnL9g+a7akJ54J0Ox2FcuBb7f23imEa47q3h9tXpBuFJ1cOmwpZtapL6yv1ZxpyLa4djE+gkfkWYzdx+COz4Ya+eqS5dG4smUD3ICocSfflWq1pnGn4oCxYmxE01rqsE5Sn4MdfRLO81W33pWfi8BW8WDw1AIZdUHl83Iiln69dHF46CyG117ALCeB7SWKx3roY/LqvKDdyCvkepN+36Lbg73bayAGneh1bFGZWZyci3TntGufEfNBypHeq94M83lzBjZp1ky1Mb6YKmYq+SIjKnZQPnI/t+kOFqaeVBO9UShmlxGx1A2mk9o34R/Yt21t13K6yAsDJ+fTtK8bWu7xcpvgE+R7//yUQW5+zHceLdc3fGOiLwbjUK3Mk5vJB5j4NEMRt32rpjIld7hNv/TIvxrqorDdh8DMoIUWYtpxVMo40chOaXjHI+OaxJluTW80EguMnVH9qfXnFvR4phycMzUp+cg96PoIGl3Lg0hNzvlkNkDvb6zp9PGtDZLIu5oDuX7/7OcUhhGLBNW4UEH2T4="
  - secure: "lox2iaU1WdUnj94T/4oJ3R2JDQBuUprKk4kbx10vKmpPjrCrzJ9DiaASO0sRMi5U03pR/PPPaRWsa/yLYzGdBPoFB2AVTiUrGBqlDvqD9mBfFRo55Y1G6QERPOd0/EVol9T1TJKCIAd4lEnlp86HXaHJnfnUWhVm0UXnSjGYUEvmlmtmb1Bq4TibQq8mgEaO/h/cb+bHcNVk1vLrEhrVKtDLU/paDTTnSSlmg86O/+ZS4q3gZGbM8mKsItcp55nrt6/Tjfkyyuqzh/N+O8ori9bVbpJhQqEubjfFAzJhPk3ygLodL/OzWagVN4mOZ8mrUi4oA5JsypCawTneOEDRSymR1+6G+KAXQT0bSo+baLzeukyX9bReCKV8MI16kXrpuoxATRseXO9IMdQCVDYOe+z6TiXP4Xe8Rg25xquDerdiw0Yopou8fAM45IDo4fQgklzp6G0V9g8QFJPz95g2wB2aKIxRKHnDeDDyWziB87FYr9N2e53T99FAIEE8TnRCcktdzDVyu+2oZ5jeU2eTkm2yjfbIEea3xEqOl0nH6ifv/MsvUE6ZSghBIi8qt0zN94H3kXevsFrPajml0zJekifK+143fWpQzbve1aFwqjGopL8d0p0K+SwN2BFINWTlvRhbjvZOb29VFx/30G+atnlmMFjU8meObExxDyIUjUU="
  - secure: "A0KXfd7AkB0+ShNUpVWuKWGcQsbmBTQAlL3WoLc+Bi4KjwXB98A1xBZUin9SHJL4h3diIPsLKPVhsfJJJ8SVFt3vZ7k9BZQ4y1KkmQpidjaKu4+kxxd9la1ln16JrMSrevfdsdOIkXHbvzuz6goY8Z5LcG2dM+WLtHcdFZk/nSynS3dxObGy1TI5bE8Vp9/5UWX0IIP96TemtAHXaZe9/+0s5OpDH90P10aqi/4P7wIyDiy3df94QhyqXZb48QiO7DjkawQiBaD/swQBXcbyAKgGhPc2yrThQKXYI13Oe5i1vWuPZUEqQ6/sJoz/x3kyBaW4pnrhaPDujnYJ6d+EollSmKb6aJaUc7F590z/0r6nTvSg6b2zxDQh2cbMplGoQj5KmESJmsqMbWKIesP6IKWP8TTYS2G/8uq/6n4BL+5mafsaIrxDNmi/LcrhdtVNfN37RJMmohg/FQG+DSawepClbPidd63FBSieAm4iRUdJGoLXm7wb6bF5a4cRd+yuepkXa8fin0pf17pytbKrsGTi2UzvKmFAf4a9HgLELowHh+dsVOJJ5NmV5i2DXYxdnYQrTrS7Nv4pLWvxIheFvchao+tzHN3kbdSldpgNMOjFGK/6xWE3lQt7OIkflhY7VwLoShzqq2f6rheQyaHoHAkhg4SyhJBcO4xoqFRdoco="
  - secure: "S4uwI/OAKkhcOuMIqB/YGgwV7jDkkdqiJAZGJNEPzc60oPN+9x45D9wHtEo7VLUx6YXBGyiAKxpvSlTn/lWvJMkioUc3O4gD24g7P4ea470jyhbIsFLldmV+A3fT/GRPtC41tHoPUAqLTKeHzNC0gluDn/c+FmgwyM3YGlQ6lmABQxV5vT6cUEvr2CEO1L8F9k+eEnsQbKa73AEUH+X35UwyV+Qf2YU+oKy3ihM04kBhhvwpCsxDazMXkjlNJuDCnpZBOE8QpyqrmxRHbcUit+rpDKl5XMAqanQLRdApACnVYqjCwdikrNf0ObSsvUHoYnbCerU1CAPrR8md5+BOEr6JG3fGGqlEdkKd6HT8zaMul/aeCK+aQOu3646TiOCJ68EcVIZ84N0zJeHaDX4fbNIrvHJXpZ5L3mqVaziIy6VuHry2neI8upQZ6gDBMaT5Nd2FZrJ5XbNFFXU/5hFA9fS8bteUMOcwJ7WMDNabjmTc4FdVULwCHDQI0Ze/BQtttPu8/prIHGH2iOVmMCFwpSenxZ64+pg59M0jSLC3QUdkxDCTBi8NdKXNqHfmBD8yQ4Y4lf98Nydt/JCFzlelspZMqFsFkz5ww7IBm4ivXXZnw/K4TIpqMP+OWcgHfaLd4oT9wu66J8aaEsefW5C7Hv6Oas6CeyHRiE5l3G1zVHE="

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  apt: true
  directories:
  - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

before_script:
- npm run lint
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${STAGING_BRANCH}"
