language: node_js

node_js:
- '6'

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=develop
  - AWS_REGION=us-east-1
  - AWS_ECS_CLUSTER=ruralroads
  - DOCKER_SRC_IMAGE=rra-dashboard
  - DOCKER_REPOSITORY=wbtransport/rra-dashboard
  - secure: JSB/k1PDAdj/SL7m3IYen+0MqfYcmCkFluIWXaCRSuGE9Dk8Y9+35iW3iAEPhDLuHdImwy28hzsCeM1gYhgGbcI4cYASbpj99DK7ehrnqki1D8b/0odDwq5iU83FElHLZBEoF8vAtSFGMjKQeDnb+vuD7InQyaIt0N3mKFGdN2SE8w4SooPpt3D5XJ5d0eeTcJL6hezxxR+0V7hx14rV2LPR2JUrxXXwYGJv3OnEneBL+5FzWPV2KpaHOwmI0zGjh50f1YrZOIjoIKxA98hKIf5OPQBdgU84mizyRbv103o6D6Q5+RWtuouWLcZHO6TlRbUkYzcaPK5jcxZWqEk/oFwo4/GGXg3/InBx5MHGqdCRArTSxYNRGkogHpAIyMqBZFpS0qcS+L3dn4O+pmH2v8mo8j7SU5Kwlvpc9WmtvjnTNi0qZHnari/wVOzFuFC4tlWKH5J+tjGIcY1bYw89RxC0MW1T4hyLKn/GM61RwWsW7hF7PQYVS412Ea+s9iAMuUfZqvewNzJKIKu4+U5tL8yv3ySlfsL0E9bNE/oS8Sthv71mWNmT9riFFcZpDvQjR+cs1ccM3YeekhVLz4RRgccNfdt1VKTcENJ+POn+666DuTAq4gHDZhbW24fQ2rWi8qR2UrjFhNQwAIl/uVp34ZFesvQSVm0Xr3T3lLaGM5M=
  - secure: Vr+l7TUUyGu92+U6m7+U9QqCeO8u/HFxKpZE/q2BHMm7BpqFPHqmdJOI0Bs8pQz0Wm4A47gWKqiT0vJW6+eoOmef2AiE9DPQXD3KbyRpTB5z2r7GwmQPYHMvJX19gtn+duhKHOFRYfmsJ/sDx93Y6OMHYS901qdcbsuhTfKN/NClZNfNNuW5OnsIPYIBcTdlzym8JdBeH+ngswFDgBkqUHJjTAxS9ECyRKKX2DEz6SiU6pHu6hRLaSF+rmCjAV9KOGrXquvXEm/UKRRbzdQcR7ZBLObwW1O49R+Bq0GeasVQT3GjhEzgUK5kpQZcbY7lO9ag2k6YvrnPiZWR4jooxpChdGwpJ579bSnpLSeIM6SMNDXINTJaVJt8ns++opxe8GSNujdzImLIAzctQS0Lzq4tN+WPEZD7EkAythoxjV5Xh8U/EZZpQHEkonFbJtY3Nkj920jn1uh6+sQ+y+Abf+pzTkAsb/fleZJ0ytJ/Y6a1bp5GkljYbsOVHjAqVs8AjgCoCQN27n0A58/DMSo0PbV4uvXh+NBHBSc07156eWTz6fRGRUpMLiLfcAwSwczK/AuAJN47SAJU9PLUxnsIj26ZMF718fOJNdxDLbl27gLlvUOaYVFk7QeSFTMQ4zO7CSBjjUqI6FDvAmkNSwAoerLGUO7u3mP8cj4H4XNoENI=
  - secure: "A0KXfd7AkB0+ShNUpVWuKWGcQsbmBTQAlL3WoLc+Bi4KjwXB98A1xBZUin9SHJL4h3diIPsLKPVhsfJJJ8SVFt3vZ7k9BZQ4y1KkmQpidjaKu4+kxxd9la1ln16JrMSrevfdsdOIkXHbvzuz6goY8Z5LcG2dM+WLtHcdFZk/nSynS3dxObGy1TI5bE8Vp9/5UWX0IIP96TemtAHXaZe9/+0s5OpDH90P10aqi/4P7wIyDiy3df94QhyqXZb48QiO7DjkawQiBaD/swQBXcbyAKgGhPc2yrThQKXYI13Oe5i1vWuPZUEqQ6/sJoz/x3kyBaW4pnrhaPDujnYJ6d+EollSmKb6aJaUc7F590z/0r6nTvSg6b2zxDQh2cbMplGoQj5KmESJmsqMbWKIesP6IKWP8TTYS2G/8uq/6n4BL+5mafsaIrxDNmi/LcrhdtVNfN37RJMmohg/FQG+DSawepClbPidd63FBSieAm4iRUdJGoLXm7wb6bF5a4cRd+yuepkXa8fin0pf17pytbKrsGTi2UzvKmFAf4a9HgLELowHh+dsVOJJ5NmV5i2DXYxdnYQrTrS7Nv4pLWvxIheFvchao+tzHN3kbdSldpgNMOjFGK/6xWE3lQt7OIkflhY7VwLoShzqq2f6rheQyaHoHAkhg4SyhJBcO4xoqFRdoco="
  - secure: "S4uwI/OAKkhcOuMIqB/YGgwV7jDkkdqiJAZGJNEPzc60oPN+9x45D9wHtEo7VLUx6YXBGyiAKxpvSlTn/lWvJMkioUc3O4gD24g7P4ea470jyhbIsFLldmV+A3fT/GRPtC41tHoPUAqLTKeHzNC0gluDn/c+FmgwyM3YGlQ6lmABQxV5vT6cUEvr2CEO1L8F9k+eEnsQbKa73AEUH+X35UwyV+Qf2YU+oKy3ihM04kBhhvwpCsxDazMXkjlNJuDCnpZBOE8QpyqrmxRHbcUit+rpDKl5XMAqanQLRdApACnVYqjCwdikrNf0ObSsvUHoYnbCerU1CAPrR8md5+BOEr6JG3fGGqlEdkKd6HT8zaMul/aeCK+aQOu3646TiOCJ68EcVIZ84N0zJeHaDX4fbNIrvHJXpZ5L3mqVaziIy6VuHry2neI8upQZ6gDBMaT5Nd2FZrJ5XbNFFXU/5hFA9fS8bteUMOcwJ7WMDNabjmTc4FdVULwCHDQI0Ze/BQtttPu8/prIHGH2iOVmMCFwpSenxZ64+pg59M0jSLC3QUdkxDCTBi8NdKXNqHfmBD8yQ4Y4lf98Nydt/JCFzlelspZMqFsFkz5ww7IBm4ivXXZnw/K4TIpqMP+OWcgHfaLd4oT9wu66J8aaEsefW5C7Hv6Oas6CeyHRiE5l3G1zVHE="

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  apt: true
  directories:
  - node_modules

before_install:
- chmod +x ./.build_scripts/deploy.sh

before_script:
- npm run lint
- npm test

script:
- npm run build

deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${STAGING_BRANCH}"
