language: node_js
node_js:
- '6'

env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=develop
  - DOCKER_SRC_IMAGE=rra-frontend
  - DOCKER_REPOSITORY=wbtransport/rra-frontend
  - DOCKER_USERNAME=danielfdsilva
  # DOCKER_PASSWD
  - secure: "h75xWtn6FcviGqtw0nkL1WXl+v64xsCDI3gGIZWrDg5BO5Mg2YRUARPRsoGWFL6HcHuDNdVzG/yxacwdGaGbUlLjnmUk9g/8NMWzvY/4viFduuW/WYO3JbnVzXbHhowAoFi1JyLfo3ZKi4Ci2+kcL6HqlZNJfpkAwR0j0oxc9GMZn11Wk7JWjJoU5+eUTU0MJ6cZn+hpABzw+h9VQSevU6AgxTFYAMyfCQ83PnBjZjoovK9UU98E4L1UvISw8mGUPzYVb6I45HGrQQ5Ts7dD0/3M7eHG/Wct6Rn7Jr9bdnrTXWRbOz8v8FuzWOFn3WyH9JqRbeZzA+BoO1haBVHt6uiFrEDNEPx/YPOob14eNrUgnTZW6ywd1DSbj809hrYexClgcbIvErUV2KHectv2tFNVMBGj25SgT7DvqDbqd6SuYJnCn8hU8c8OqNaimhppYHyWnGJyAcIjnqzXWy2OGRu0G/aTVnlY7KQu4RVbLBUCSveQnNoG/OdyEyx7H50mXcUXU8686MXn4KolxTsw8PTFJ3G4DVhGzMXDpx9vxCStEYV1t2Tkfwj2mUObn/K1GxyaiUKlz7wUbrQ6eV2JN71OujpVU9RSyk6bM5wYjPitf8P6Sj+/k+5XR6arR3wGMdWgJn5p5uVSCr1U2qaaC67AqYx18jq/OGp0g1KJNmY="

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  apt: true
  yarn: true
  directories:
  - node_modules

services:
  - docker

before_script:
- yarn test

script:
- yarn run build

deploy:
- provider: s3
  access_key_id: AKIAILREAKXPJOWAXTBQ
  secret_access_key:
    secure: tIcdJM91mqbv7zQCUSRNkT8OEViNBLltR6StE3QyOkUrnmMLZZ0uliSwxztuaM/BxnM5g3M4mO+MOL674HEGSyJueKlaPfFBdJAU7f3amphWdCI8KnN/SToOF9UMI3aKUFTDuYAefkD5mXCiyDehbboLCTj/USOMBGkz7McVCeNHQUy3EwtgJ2cRE6s6b22nQ+NkeTmzwXJKjYgyYh4mf+wuIJ3mVuXeUpl+pzNObNaWd4ncvgYlHGabVard6zVvqp/rGbmf/JiMZeziuxJSlFn6Hd9QM/fc2KsWy/SUYlHue4AODu33EjUwS6Hhgiw92Lf3aAq73qM2CE8WDxQBgajIiCoP2PYToMRvVneLyQ0oq3briLbRbBXdIzpB7oihxvablqUoIoNymhap96xoU+YXsW6FE1mGb6o8inGSvfR/qGykRbhB4KwRschzH+SoWp6AGucKt2i7coEDIhOcnaiq3Lphuak8uoeT4bfceMU2W/GwaM6fUk3IGyG0XsJmamXgotKcyzY4n4FPqC4riuNwOSw/OuURL17va5MWAHumQ5HCJ+EZjI3470CRcTI7+Z1AZDg7SZuqqffsRQ8Zdoyjl6Ek+/cYS3jRDl8NHETFe7p/prD1I4vcvUcB34mB0IVCrO98codSNzr+Q1gNi2xBI1FcuPaJRMMI2d/ztS0=
  bucket: staging.ram.tf
  acl: public_read
  local-dir: "./dist/"
  skip-cleanup: true
  region: us-east-1
  on:
    repo: WorldBank-Transport/ram-frontend
    branch: "${STAGING_BRANCH}"
- provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${STAGING_BRANCH}"
- provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
